p8105\_hw2\_xc2474
================

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
    ## ✔ tibble  1.4.2     ✔ dplyr   0.7.6
    ## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
    ## ✔ readr   1.1.1     ✔ forcats 0.3.0

    ## ── Conflicts ───────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(knitr)
```

Problem 1
=========

Read data
---------

import csv file

``` r
nyc_sub = read.csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

clean the data

``` r
nyc_sub_tidy = nyc_sub %>%
  janitor::clean_names() %>%
  select(line:entry, vending, ada) %>%
  mutate(entry = recode(entry, YES = TRUE, NO = FALSE))
```

This dataset contains 19 variables, which is line, station\_name, station\_latitude, station\_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entrance\_type, entry, vending, ada

My data cleaning steps are as follows: 1. import the data. 2. apply janitor::clean\_names() function to change the variable names into a more readable way (all lowercase and only contain "\_"). 3. retain the variables we want using select funtion, which will remove the variables we don't need. 4. use recode() function to change all "YES" and "NO" in entry variable into correspongding "TRUE" and "FALSE" (make entry variable to a logical variable), and use mutate() function to retain the change in nyc\_sub\_tidy dataset.

The dimension of the resulting dataset is 1868 rows x 19

I think although these data are tidier than before, but they are not tidy enough.

Question1
---------

Q1: How many distinct stations are there?

``` r
distinct(nyc_sub_tidy, station_name, line) %>%
  nrow()
```

    ## [1] 465

A: There are 465 distinct stations.

Q2: How many stations are ADA compliant?

Here we define "ADA compliant" in a broad way, which means as long as ada=TRUE, we consider this station as ADA compliant:

``` r
nyc_sub_tidy %>%
  filter(ada == TRUE) %>%
  nrow()
```

    ## [1] 468

There are 468 stations are ADA compliant.

Q3: What proportion of station entrances / exits without vending allow entrance?

``` r
nrow(filter(nyc_sub_tidy, vending == "NO")) / nrow(nyc_sub_tidy)
```

    ## [1] 0.09796574

A: The proportion of station entrances / exits without vending allow entrance is 0.09796574.

Reformat data so that route number and route name are distinct variables

``` r
nyc_sub_tidy = nyc_sub_tidy %>%
  gather(key = "route_number", value = "route_name", route1:route11) %>%
  separate(route_number, into = c('remove', 'route_number'), sep = 5) %>%
  select(-remove)
```

    ## Warning: attributes are not identical across measure variables;
    ## they will be dropped

Q: How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?

``` r
nyc_sub_tidy %>%
  filter(route_name == "A") %>%
  distinct(station_name, line) %>%
  nrow()
```

    ## [1] 60

``` r
nyc_sub_tidy %>%
  filter(route_name == "A", ada == TRUE) %>%
  distinct(station_name, line) %>%
  nrow()
```

    ## [1] 17

A: There are 60 distinct station serve the A train, and there are 17 of them are ADA compliant.

Problem 2
=========

import
